title: State of Palestine
description: An attempt to brand the liberated, modern, sovereign, Arab State of Palestine. For free use and distribution.
author: Nader Takkli
email: nadertakkli@gmail.com
url: "https://nadertakkli.github.io"
baseurl: "state-of-palestine/"
github_username: nadertakkli
repository: nadertakkli/state-of-palestine
